name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2022-07-26
version: '9.4.x-dev'
project: 'drupal'
datestamp: 1658857047
