name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-07-26
version: '9.4.x-dev'
project: 'drupal'
datestamp: 1658857047
